package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Administrador generated by hbm2java
 */
public class Administrador implements java.io.Serializable {

	private String idAdministrador;
	private String nombreAdministrador;
	private Set giroses = new HashSet(0);
	private Set giros = new HashSet(0);

	public Administrador() {
	}

	public Administrador(String idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	public Administrador(String idAdministrador, String nombreAdministrador, Set giroses, Set giros) {
		this.idAdministrador = idAdministrador;
		this.nombreAdministrador = nombreAdministrador;
		this.giroses = giroses;
		this.giros = giros;
	}

	public String getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(String idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	public String getNombreAdministrador() {
		return this.nombreAdministrador;
	}

	public void setNombreAdministrador(String nombreAdministrador) {
		this.nombreAdministrador = nombreAdministrador;
	}

	public Set getGiroses() {
		return this.giroses;
	}

	public void setGiroses(Set giroses) {
		this.giroses = giroses;
	}

	public Set getGiros() {
		return this.giros;
	}

	public void setGiros(Set giros) {
		this.giros = giros;
	}

}
