package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

/**
 * Banco generated by hbm2java
 */
public class Banco implements java.io.Serializable {

	private String idBanco;
	private String idDivisas;

	public Banco() {
	}

	public Banco(String idBanco) {
		this.idBanco = idBanco;
	}

	public Banco(String idBanco, String idDivisas) {
		this.idBanco = idBanco;
		this.idDivisas = idDivisas;
	}

	public String getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(String idBanco) {
		this.idBanco = idBanco;
	}

	public String getIdDivisas() {
		return this.idDivisas;
	}

	public void setIdDivisas(String idDivisas) {
		this.idDivisas = idDivisas;
	}

}
