package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private String idCliente;
	private Pais pais;
	private TipoCliente tipoCliente;
	private TipoDocumento tipoDocumento;
	private String nombres;
	private String apellido;
	private String razonSocial;
	private String idGiro;
	private Set biometrias = new HashSet(0);
	private Set giros = new HashSet(0);
	private Set giroses = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String idCliente, Pais pais, TipoCliente tipoCliente, TipoDocumento tipoDocumento, String nombres,
			String apellido, String razonSocial) {
		this.idCliente = idCliente;
		this.pais = pais;
		this.tipoCliente = tipoCliente;
		this.tipoDocumento = tipoDocumento;
		this.nombres = nombres;
		this.apellido = apellido;
		this.razonSocial = razonSocial;
	}

	public Cliente(String idCliente, Pais pais, TipoCliente tipoCliente, TipoDocumento tipoDocumento, String nombres,
			String apellido, String razonSocial, String idGiro, Set biometrias, Set giros, Set giroses) {
		this.idCliente = idCliente;
		this.pais = pais;
		this.tipoCliente = tipoCliente;
		this.tipoDocumento = tipoDocumento;
		this.nombres = nombres;
		this.apellido = apellido;
		this.razonSocial = razonSocial;
		this.idGiro = idGiro;
		this.biometrias = biometrias;
		this.giros = giros;
		this.giroses = giroses;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public TipoCliente getTipoCliente() {
		return this.tipoCliente;
	}

	public void setTipoCliente(TipoCliente tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public Set getBiometrias() {
		return this.biometrias;
	}

	public void setBiometrias(Set biometrias) {
		this.biometrias = biometrias;
	}

	public Set getGiros() {
		return this.giros;
	}

	public void setGiros(Set giros) {
		this.giros = giros;
	}

	public Set getGiroses() {
		return this.giroses;
	}

	public void setGiroses(Set giroses) {
		this.giroses = giroses;
	}

}
