package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

/**
 * Divisas generated by hbm2java
 */
public class Divisas implements java.io.Serializable {

	private String idDivisas;

	public Divisas() {
	}

	public Divisas(String idDivisas) {
		this.idDivisas = idDivisas;
	}

	public String getIdDivisas() {
		return this.idDivisas;
	}

	public void setIdDivisas(String idDivisas) {
		this.idDivisas = idDivisas;
	}

}
