package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

/**
 * Giro generated by hbm2java
 */
public class Giro implements java.io.Serializable {

	private String idGiro;
	private Administrador administrador;
	private Cliente cliente;
	private Empleados empleados;
	private Pais pais;
	private Sede sede;
	private String idReporte;

	public Giro() {
	}

	public Giro(String idGiro) {
		this.idGiro = idGiro;
	}

	public Giro(String idGiro, Administrador administrador, Cliente cliente, Empleados empleados, Pais pais, Sede sede,
			String idReporte) {
		this.idGiro = idGiro;
		this.administrador = administrador;
		this.cliente = cliente;
		this.empleados = empleados;
		this.pais = pais;
		this.sede = sede;
		this.idReporte = idReporte;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public Administrador getAdministrador() {
		return this.administrador;
	}

	public void setAdministrador(Administrador administrador) {
		this.administrador = administrador;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	public String getIdReporte() {
		return this.idReporte;
	}

	public void setIdReporte(String idReporte) {
		this.idReporte = idReporte;
	}

}
