package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

/**
 * Giros generated by hbm2java
 */
public class Giros implements java.io.Serializable {

	private GirosId id;
	private Administrador administrador;
	private Cliente cliente;
	private Sede sede;

	public Giros() {
	}

	public Giros(GirosId id) {
		this.id = id;
	}

	public Giros(GirosId id, Administrador administrador, Cliente cliente, Sede sede) {
		this.id = id;
		this.administrador = administrador;
		this.cliente = cliente;
		this.sede = sede;
	}

	public GirosId getId() {
		return this.id;
	}

	public void setId(GirosId id) {
		this.id = id;
	}

	public Administrador getAdministrador() {
		return this.administrador;
	}

	public void setAdministrador(Administrador administrador) {
		this.administrador = administrador;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

}
