package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private String idPais;
	private String nombrePais;
	private String idGiros;
	private Set locutorios = new HashSet(0);
	private Set giros = new HashSet(0);
	private Set clientes = new HashSet(0);

	public Pais() {
	}

	public Pais(String idPais) {
		this.idPais = idPais;
	}

	public Pais(String idPais, String nombrePais, String idGiros, Set locutorios, Set giros, Set clientes) {
		this.idPais = idPais;
		this.nombrePais = nombrePais;
		this.idGiros = idGiros;
		this.locutorios = locutorios;
		this.giros = giros;
		this.clientes = clientes;
	}

	public String getIdPais() {
		return this.idPais;
	}

	public void setIdPais(String idPais) {
		this.idPais = idPais;
	}

	public String getNombrePais() {
		return this.nombrePais;
	}

	public void setNombrePais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	public String getIdGiros() {
		return this.idGiros;
	}

	public void setIdGiros(String idGiros) {
		this.idGiros = idGiros;
	}

	public Set getLocutorios() {
		return this.locutorios;
	}

	public void setLocutorios(Set locutorios) {
		this.locutorios = locutorios;
	}

	public Set getGiros() {
		return this.giros;
	}

	public void setGiros(Set giros) {
		this.giros = giros;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
