package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

/**
 * ReporteGiro generated by hbm2java
 */
public class ReporteGiro implements java.io.Serializable {

	private ReporteGiroId id;

	public ReporteGiro() {
	}

	public ReporteGiro(ReporteGiroId id) {
		this.id = id;
	}

	public ReporteGiroId getId() {
		return this.id;
	}

	public void setId(ReporteGiroId id) {
		this.id = id;
	}

}
