package co.edu.campusucc.sd.modelo;
// Generated 29/03/2020 10:52:29 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede implements java.io.Serializable {

	private String idSede;
	private String nombreSede;
	private Set giroses = new HashSet(0);
	private Set giros = new HashSet(0);

	public Sede() {
	}

	public Sede(String idSede) {
		this.idSede = idSede;
	}

	public Sede(String idSede, String nombreSede, Set giroses, Set giros) {
		this.idSede = idSede;
		this.nombreSede = nombreSede;
		this.giroses = giroses;
		this.giros = giros;
	}

	public String getIdSede() {
		return this.idSede;
	}

	public void setIdSede(String idSede) {
		this.idSede = idSede;
	}

	public String getNombreSede() {
		return this.nombreSede;
	}

	public void setNombreSede(String nombreSede) {
		this.nombreSede = nombreSede;
	}

	public Set getGiroses() {
		return this.giroses;
	}

	public void setGiroses(Set giroses) {
		this.giroses = giroses;
	}

	public Set getGiros() {
		return this.giros;
	}

	public void setGiros(Set giros) {
		this.giros = giros;
	}

}
